### ISSUE TITLE
Port mandatory and defaults to 0

### ISSUE THREAD

**Issue by fadams1** [iZettle/dropwizard-metrics-influxdb#70] opened 2017-06-16 13:10 UTC
If I do not provide a port (because my influx URL has an alias assigned) then a default of 0 is used rather than accept the URL as it is.

E.g. Full production URL of my influx db = http://my-company-influx.com

**Comment by e-vrvr** [comment] 2017-11-19 22:17
Have the same issue. You can always try to set port as default http/https - 80/443 for example

**Comment by rickard-von-essen-iz** [comment] 2017-11-20 07:51
Which version are you using?

From the code it seems like it defaults to `8086`.

```java
    @Range(min = 0, max = 49151)
    private int port = 8086;
```

See [here](https://github.com/iZettle/dropwizard-metrics-influxdb/blob/master/dropwizard-metrics-influxdb/src/main/java/com/izettle/metrics/dw/InfluxDbReporterFactory.java#L155-L156)

**Comment by e-vrvr** [comment] 2017-11-20 09:36
@rickard-von-essen-iz, I believe the question was more - if I have entire influxdb host:port combination mapped to domain like _company.com_, how should I use it since reporter always tries to use port, either default or taken from properties.
I've managed to do this setting reporter port to 80 for my influxdb instance.
Hope someone will find this helpful.

p.s. the version is 1.1.9

**Comment by rickard-von-essen-iz** [comment] 2017-11-20 10:07
Sorry I'm not sure I understand.

What do you mean with:

> if I have entire influxdb host:port combination mapped to domain like company.com

**Comment by e-vrvr** [comment] 2017-11-20 11:26
InfluxDb is hidden behind proxy, and accessible from outside only by url http://influxdb.mycompany.com/.

**Comment by rickard-von-essen-iz** [comment] 2017-11-20 12:05
So `port: 80`?

**Comment by e-vrvr** [comment] 2017-11-21 11:40
yes, thas was what I wrote:
> You can always try to set port as default http/https - 80/443 for example
I saw this question in open issues, and for me it looks like not an issue at all - merely not straightforward, so  I added my comment.
Thanks for your responses.

**Comment by rickard-von-essen-iz** [comment] 2017-11-23 11:03
I'll close this since I think this works as intended. Please clarify what is the problem if you still think this is a bug/missing feature.

**Closed by rickard-von-essen-iz** 2017-11-23 11:03 UTC
Labels: need-more-info, waiting-reply
